### ISSUE TITLE
API bundle compatibility with composer latest version 2.0

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/api-bundle#10]
getting the below error when installing API bundle

![Screenshot_225](https://user-images.githubusercontent.com/43210406/105030338-a7576f80-5a79-11eb-8176-62e34f076192.png)

**Comment by ToddE** [comment]
maybe related -- documentation does warn not to use the latest symfony -- also php8 not supported. Installer doesn't recognize php8 as > 7.0

![image](https://user-images.githubusercontent.com/3709322/140093863-646e0a13-98a8-4c94-b22d-bf1a3cdfbfb9.png)

**Comment by papnoisanjeev** [comment]
@ToddE 

Please check now if you are still facing this issue.
We have recently made updates for the same.
