### ISSUE TITLE
Cannot download attachment from uvdesk api bundle

### ISSUE THREAD

**Issue by phenomenalDenzel** [uvdesk/api-bundle#11]
Route for downloading an attachment "http://localhost:8000/api/v1/ticket/attachment/{attachementId}" is not working, when accessing the api-bundle provided by uvdesk
  
Every time i try to download an attachment using the above route, i kept on getting response:
{
    "status": false,
    "message": "An unexpected error occurred. Please try again later."
}

**Comment by papnoisanjeev** [comment]
@phenomenalDenzel 

For download attachment issue locate path:
**vendor/uvdesk/api-bundle/API/Tickets.php**

Open **Tickets.php** and replace your **Tickets.php** code from [here](https://github.com/uvdesk/api-bundle/blob/master/API/Tickets.php).
