### ISSUE TITLE
create with multiple attachments

### ISSUE THREAD

**Issue by temiotu** [uvdesk/api-bundle#12]
When i upload multiple attachments to uvdesk, it only uploads the last file in the set of files sent, and discards the rest. 
It does not accept an array of files when creating a ticket or replying to a ticket. It only takes one.

**Comment by papnoisanjeev** [comment]
@temiotu 

Locate path in your project:
**vendor/uvdesk/api-bundle/API/Tickets.php**

Open **Tickets.php** and replace this [line ](https://github.com/uvdesk/api-bundle/blob/master/API/Tickets.php#L210) by below code for ticket create.

**$attachments[] = $request->files->get('attachments');**

For Ticket Reply:
**vendor/uvdesk/api-bundle/API/Threads.php**

Open **Threads.php** and replace this [line ](https://github.com/uvdesk/api-bundle/blob/master/API/Threads.php#L80) by below code for ticket create.

**$attachments[] = $request->files->get('attachments');**

And make a try if it works.

**Comment by papnoisanjeev** [comment]
@temiotu 

Hope issue is fixed so closing it if still exist you can reopen it.

**Comment by papnoisanjeev** [comment]
@phenomenalDenzel

Please check below screen shots after update:

**For single attachment Using postman:**

https://prnt.sc/zbkpc5

![SingleAttachmentPostman](https://user-images.githubusercontent.com/42460055/107846987-11133100-6e0e-11eb-8a20-f9c1cffed3c2.PNG)


**For multiple attachment Using postman:**

https://prnt.sc/zbl4s2

![MultipleAttachment](https://user-images.githubusercontent.com/42460055/107847028-428bfc80-6e0e-11eb-87f7-02a51c9b0da0.PNG)

Make a try again and verify data first and request as we are doing from postman.

**Comment by phenomenalDenzel** [comment]
Yes I did the that still ends up uploading just one file.

The Request: 
![Screen Shot 2021-02-13 at 11 05 47 AM](https://user-images.githubusercontent.com/52481771/107847525-9554bc80-6dec-11eb-8b72-7e5bf3262dbd.png)

Verified data on uvdesk UI:
![Screen Shot 2021-02-13 at 11 06 20 AM](https://user-images.githubusercontent.com/52481771/107847551-db118500-6dec-11eb-8013-57c84806cc64.png)

Also after getting the newly created ticket with the API route "localhost:8000/api/v1/ticket/77", it shows the ticket has only one attachment.
![Screen Shot 2021-02-13 at 11 17 07 AM](https://user-images.githubusercontent.com/52481771/107847709-09439480-6dee-11eb-8d75-efe47b6b2f88.png)

**Comment by papnoisanjeev** [comment]
@phenomenalDenzel 

**attachments[]** (we have shown this to you with our multiple attachment screenshot) try this when sending more than one file it should be a array.

**Comment by phenomenalDenzel** [comment]
@papnoisanjeev 
Ok Sorry about that, Let me quickly try that with the array symbol

**Comment by phenomenalDenzel** [comment]
@papnoisanjeev

Thank you very much. It works now

**Comment by papnoisanjeev** [comment]
> @papnoisanjeev
> 
> Thank you very much. It works now

Glad to know it's working for you. 
stay tuned with us [here](https://github.com/uvdesk/community-skeleton) for updates.
