### ISSUE TITLE
 API GET tickets ActAsType customer

### ISSUE THREAD

**Issue by akaenko** [uvdesk/api-bundle#14]
**Description**  
Fetching all Tickets actAsType: customer responds with wrong list , same as agent, full long list of all tickets.

**How to reproduce**  
API GET tickets ActAsType customer

**Possible Solution**  
line 34 $data['actAsEmail'] not defined in api-bundle/API/Tickets.php
line 45 similar

**Comment by papnoisanjeev** [comment]
@akaenko 

Updated this [here](https://github.com/uvdesk/api-bundle/commit/1873be43b53812d6521b3f8d95565e7929429737).

**Comment by akaenko** [comment]
It will still fail at line 46

change: $data['actAsEmail'] 

with $request->query->get('actAsEmail')

**Comment by papnoisanjeev** [comment]
@akaenko 

Fixed [here](https://github.com/uvdesk/api-bundle/commit/a0e9f852f6bde1adae0875fdae857bdc3bc1ff3f).
