### ISSUE TITLE
I can't fetch tickets belonging to a particular email

### ISSUE THREAD

**Issue by ricardotormo** [uvdesk/api-bundle#16]
**Description**  

I'm trying to fetch the tickets belonging to a particular user. 
As suggested by the API documentation (https://github.com/uvdesk/api-bundle/wiki/Ticket-Related-APIs) I tried:
To send a GET request to this endpoint: {my_localhost_url}/api/v1/tickets?actAsEmail={email@email.com}.

The API response is the same everytime, regardless of the email parameter. 
So to clarify, everytime I receive a response containing all the tickets no matter their emails.

If I try this:
{my_localhost_url}/api/v1/tickets?actAsEmail={email@email.com}&actAsType=customer
The API returns an error.

**How to reproduce**  

To reproduce this issue:
1. Donwload and install uvdesk-community-skeleton.
2. Install the api-bundle.
3. Set up your api, following these steps: https://www.uvdesk.com/en/blog/api-resource/.
4. Open Postman and try to fetch tickets belonging to a particular email using the above mentioned method.

Thanks for your help.

**Comment by papnoisanjeev** [comment]
@ricardotormo 

Added updates on master branch.

**Comment by ricardotormo** [comment]
Great! Thank you!
