### ISSUE TITLE
Doctorine Migration version issue UVdesk

### ISSUE THREAD

**Issue by raju756** [uvdesk/api-bundle#20]
when I m trying to install I m getting this error message regarding the   doctrine/migrations package veriosn currently we are using PHP 8. please guide me. 
![image (4)](https://user-images.githubusercontent.com/51367200/149147092-a89aaab9-10d9-4c03-9e9a-148149c50ea5.png)

**Comment by vipin-shrivastava** [comment]
@raju756

We have already resolved this issue, Please check

**Comment by Komal-sharma-2712** [comment]
We are closing this issue. If you are facing the same issue so reply on the same issue thread.
