### ISSUE TITLE
API giving 404

### ISSUE THREAD

**Issue by sinkillerj** [uvdesk/api-bundle#3]
https://www.uvdesk.com/en/blog/api-resource/

I installed the API using the following guide the above guide, however when I attempt to pull for example tickets.json or similar using curl I get back a "404: We were not able to find the page you are looking for." page instead.

Am I missing a step here? The API section of the panel is available, and a token has been created.

**Comment by papnoisanjeev** [comment]
@sinkillerj 

Check this: https://github.com/uvdesk/api-bundle/issues/2

It will be helpful if still you face this issue you can create a support ticket https://support.uvdesk.com/en/customer/create-ticket/ or mail us support@uvdesk.com here.

**Comment by papnoisanjeev** [comment]
@sinkillerj
Is this issue resolve or you need any help?
