### ISSUE TITLE
Wrong variable name

### ISSUE THREAD

**Issue by ysmnikhil** [uvdesk/api-bundle#4]
https://github.com/uvdesk/api-bundle/blob/0b5e2d1bf4d5216bf32b3ec924603d9e1343c8f9/API/Tickets.php#L38

It should be `userRepository`

**Comment by papnoisanjeev** [comment]
Hello @ysmnikhil,

Thanks for notifying us.
We are going to publish a new release today and all the things will shored out with some more ticket related API.
