### ISSUE TITLE
Unable to assign ticket type when creating

### ISSUE THREAD

**Issue by menachemkorf** [uvdesk/api-bundle#6]
**Description**  
When creating a ticket using the api bundle it gets the default ticket type even when sending a type field with the request.

**How to reproduce**  
Create two Ticket Types in the dashboard

-  default
-  support

Send a `POST` request to `my-domain/api/v1/ticket` with
```json
{
    "name": "John Dow",
    "from": "john@example.com",
    "subject": "Example",
    "message": "Testing example.",
    "type": "support"
}
```

The newly created ticket has the `default` ticket type.

**Possible Cause**  
In `Webkul\UVDesk\ApiBundle\API\Tickets::createTicket` we don't do anything with `$data['type']`

**Comment by papnoisanjeev** [comment]
@menachemkorf 

https://github.com/uvdesk/api-bundle/blob/master/API/Tickets.php#L217

Add "type" in this array and make a try.

**Comment by menachemkorf** [comment]
@papnoisanjeev no, adding `'type'` to `$extraKeys` didn't work, 

I fixed it by adding the following code to the `create` function 

```php
if (array_key_exists('type', $data)) {
    $ticketType = $entityManager->getRepository('UVDeskCoreFrameworkBundle:TicketType')->findOneByCode($data['type']);

    $ticketData['type'] = $ticketType;
}
```

**Comment by papnoisanjeev** [comment]
@menachemkorf 

Glad to know that it is working for you !!
We will also add ticket type in next release.

**Comment by menachemkorf** [comment]
Any idea when this will happen?

**Comment by papnoisanjeev** [comment]
@menachemkorf 

Most probably end of this month or may be first or second week of next month.
As we will try to add some new more APIs in next release.
