### ISSUE TITLE
No route found

### ISSUE THREAD

**Issue by vstefanoxx** [uvdesk/api-bundle#7]
**Description**  
I cannot query the API for customers: I get "No route found"

**How to reproduce**  
Query for retrieving tickets works:
```console
$ curl -X GET -H "Authorization: Basic $TOKEN" https://<domain>/api/v1/tickets
```

while for customers it doesn't work:
```console
$ curl -X GET -H "Authorization: Basic $TOKEN" https://<domain>/api/v1/customers
{"status":false,"message":"No route found for \u0022GET \/api\/v1\/customers\u0022"}
```

I'm looking at the documentation on uvdek web site at the page <https://www.uvdesk.com/en/api-doc/>, but I'm getting confused because it doesn't seem to be consistent to my installation: is that documentation valid for `uvdesk/api-bundle` project?

Thank you
Stefano

**Comment by papnoisanjeev** [comment]
@vstefanoxx 

Currently only ticket related API exist for UVdesk opensource.
You can check [here](https://github.com/uvdesk/api-bundle/wiki/Ticket-Related-APIs).

We will soon work for other API's as well.

>I'm looking at the documentation on uvdek web site at the page https://www.uvdesk.com/en/api-doc/, but I'm getting confused because it doesn't seem to be consistent to my installation: is that documentation valid for uvdesk/api-bundle project?

This https://www.uvdesk.com/en/api-doc/ doc is for [UVdesk SAAS version](https://www.uvdesk.com/en/) only (subscription based).
