### ISSUE TITLE
Create new ticket with attachment

### ISSUE THREAD

**Issue by mikelga** [uvdesk/api-bundle#8]
Hi! 

I am using Python to create new tickets with this code:

```
import requests

headers = {"Authorization": "Bearer TOKEN"}

payload = {
    "message": "Ticket Message",
    "actAsType": "customer",
    "name": "Name",
    "subject": "Ticket Subject",
    "from": "client@client.com",
}

r = requests.post("http://my_server/api/v1/ticket", data=payload, headers=headers)

print r.content
```

Now I want to know how can I create this same ticket but with attachment. 

Thanks!

**Comment by papnoisanjeev** [comment]
@mikelga
try with **attachments** key.

**Comment by mikelga** [comment]
> @mikelga
> try with **attachments** key.

I have tried with "attachments": "text", but I have not got any result.

**Comment by papnoisanjeev** [comment]
@mikelga 

Try with "attachments": "file"

**Comment by mikelga** [comment]
In what format need to go the attachments variable value:
I have tried with this cope sample but it does not upload any attachment:
```
import requests

with open("data_file.json", "rb") as file:
  f = file.read()

headers = {"Authorization": "Bearer TOKEN"}

payload = {
    "message": "Ticket Message",
    "actAsType": "customer",
    "name": "Name",
    "subject": "Ticket Subject",
    "from": "client@client.com",
    "attachments": f
}

r = requests.post("http://my_server/api/v1/ticket", data=payload, headers=headers)

print r.content
```

**Comment by mikelga** [comment]
> @mikelga
> 
> Try with "attachments": "file"

In what format need to go the attachments variable value?
I have tried with this cope sample but it does not upload any attachment:

```
import requests

with open("data_file.json", "rb") as file:
  f = file.read()

headers = {"Authorization": "Bearer TOKEN"}

payload = {
    "message": "Ticket Message",
    "actAsType": "customer",
    "name": "Name",
    "subject": "Ticket Subject",
    "from": "client@client.com",
    "attachments": f
}

r = requests.post("http://my_server/api/v1/ticket", data=payload, headers=headers)

print r.content
```

**Comment by phenomenalDenzel** [comment]
I have this same issue, I cant still create a ticket with an attachment. Please can you show an example on how to do that in code. Thank You.

**Comment by papnoisanjeev** [comment]
@mikelga @phenomenalDenzel 

**1.**  For **creating ticket** attachment issue Locate path in your project:
**vendor/uvdesk/api-bundle/API/Tickets.php**
open **Tickets.php** and make change as done in below link:

https://github.com/uvdesk/api-bundle/blob/master/API/Tickets.php#L215
or directly copy and replace your existing file code from [here](https://github.com/uvdesk/api-bundle/blob/master/API/Tickets.php).

**2.** For **ticket reply** attachment issue Locate path in your project:

**vendor/uvdesk/api-bundle/API/Threads.php**
open **Threads.php** and make change as done in below link:

https://github.com/uvdesk/api-bundle/blob/master/API/Threads.php#L84
or directly copy and replace your existing file code from [here](https://github.com/uvdesk/api-bundle/blob/master/API/Threads.php).

**Comment by phenomenalDenzel** [comment]
Hy. Thank you very much for the reply.  When i upload multiple attachments to uvdesk, it only uploads the last file in the set of files sent, and discards the rest. It is just like uvdesk does not accept an array of files when creating a ticket or replying to a ticket. It only takes one. Please help.

**Comment by papnoisanjeev** [comment]
@phenomenalDenzel @mikelga 
Issue has been fixed.
Check this: https://github.com/uvdesk/api-bundle/issues/12#issuecomment-777189057
