### ISSUE TITLE
Can not reply a thread

### ISSUE THREAD

**Issue by phenomenalDenzel** [uvdesk/api-bundle#9]
**How to reproduce**  
I created a ticket using the API
![Screenshot from 2020-12-10 19-20-04](https://user-images.githubusercontent.com/52481771/101814076-e959d100-3b1d-11eb-9711-38a0f314c83b.png)

I made a post request **http://localhost:8000/api/v1/ticket/1/thread** to reply the thread, and  below is the body
`
{
  "message":"why should I Help you",
  "actAsType":"customer",
  "actAsEmail":"emeka@gmail.com",
  "threadType":"reply"
}`
This is the response and no error message in the terminal
`{
    "status": false,
    "message": "An unexpected error occurred. Please try again later."
}`

**Comment by papnoisanjeev** [comment]
@phenomenalDenzel 

We have fixed it for master branch please update your code as done in below link in your project.

Locate path in your project:
**vendor->uvdesk->api-bundle->API->Threads.php**

Open **Threads.php** and update code under **saveThread()** function.
and update code as done same in below link replace **$customer** by **$user**

https://github.com/uvdesk/api-bundle/commit/ee90d351c640199ceba9640322d71c1c4c4439b8

**Comment by papnoisanjeev** [comment]
@phenomenalDenzel,

We are closing it you can solve it by above given solution.
If still exist you can reopen it.
